version: '3.7'
services:

  hydra:
    image: oryd/hydra:v1.11.7
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - ./quickstart/configs/hydra:/etc/config/hydra

    environment:
      - DSN=mysql://root:youShouldChangeThis@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate

  hydra-migrate:
    image: oryd/hydra:v1.11.7
    environment:
      - DSN=mysql://root:youShouldChangeThis@tcp(mysqld:3306)/mysql?max_conns=20&max_idle_conns=4
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - ./quickstart/configs/hydra:/etc/config/hydra
    restart: on-failure

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.11.7
    ports:
      - "3000:3000"
    restart: unless-stopped