sys:
  apisix:
    endpoint: http://apisix:9080
    api_key: edd1c9f034335f136f87ad84b625c8f1
    upstreams:
      api-docs:
        nodes:
          "api_docs:8080": 1
        type: roundrobin
      web:
        nodes:
          "web:8080": 1
        type: roundrobin

      jaeger:
        nodes:
          "jaeger-all-in-one:16686": 1
        type: roundrobin

      kafka-ui:
        nodes:
          "kafka-ui:8080": 1
        type: roundrobin

      dtm-ui:
        nodes:
          "dtm:36789": 1
        type: roundrobin

      hydra-public:
        nodes:
          "hydra:4444": 1
        type: roundrobin

    global_rules:
      opentelemetry:
        plugins:
          opentelemetry:
            sampler:
              name: always_on
      kit_authn:
        plugins:
          ext-plugin-pre-req:
            conf:
              - name: "kit_authn"
                value: "{}"
      cors:
        plugins:
          cors:
            allow_origins: "*"
    routes:
      hydra-public:
        uris: [ "/.well-known/jwks.json","/.well-known/openid-configuration","/oauth2/*","/userinfo" ]
        upstream_id: hydra-public
        priority: 100

      api-docs:
        uri: /swagger*
        upstream_id: api-docs

      jaeger:
        uri: /jaeger*
        upstream_id: jaeger
        plugins:
          ext-plugin-pre-req:
            conf:
              - name: "kit_authz"
                value: "{\"requirement\":[{\"namespace\":\"dev.jaeger\",\"resource\":\"*\",\"action\":\"*\"}]}"
      kafka-ui:
        uri: /kafka-ui*
        upstream_id: kafka-ui
        plugins:
          ext-plugin-pre-req:
            conf:
              - name: "kit_authz"
                value: "{\"requirement\":[{\"namespace\":\"dev.events.kafka\",\"resource\":\"*\",\"action\":\"*\"}]}"
          response-rewrite:
            headers:
              X-Frame-Options: ""

      dtm-ui:
        uris: ["/dtm-ui*","/api/dtmsvr*"]
        upstream_id: dtm-ui
        plugins:
          ext-plugin-pre-req:
            conf:
              - name: "kit_authz"
                value: "{\"requirement\":[{\"namespace\":\"dev.dtm\",\"resource\":\"*\",\"action\":\"*\"}]}"

      payment-api:
        uris: ["/v1/payment/*","/v1/subscription*","/assets/payment/*"]
        upstream_id: payment-http

      order-api:
        uris: ["/v1/order*","/assets/order/*"]
        upstream_id: order-http

      product-api:
        uris: ["/v1/product","/v1/product/*","/assets/product/*"]
        upstream_id: product-http

      realtime-api:
        uris: ["/v1/realtime/*","/assets/realtime/*"]
        upstream_id: realtime-http
        enable_websocket: true

      saas-api:
        uris: ["/v1/saas/*","/assets/saas/*"]
        upstream_id: saas-http

      sys-api:
        uris: ["/v1/sys/*","/v1/oidc/*","/assets/sys/*"]
        upstream_id: sys-http

      user-api:
        priority: -99
        uris: ["/v1/*","/assets/user/*"]
        upstream_id: user-http

      web:
        priority: -100
        uri: /*
        upstream_id: web
